<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import random
import numpy as np

**ZigZag Traverse**

In [14]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

print(inMatrix)

[[4 5 9 7 9 2 3 3]
 [1 8 6 2 4 8 1 8]
 [5 5 2 8 7 8 7 9]
 [5 9 0 1 0 7 6 1]
 [4 7 2 7 7 5 0 7]
 [1 8 9 4 3 7 0 7]
 [7 0 3 4 5 5 1 2]
 [3 6 0 4 1 1 2 8]]
