<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np
import heapq
import timeit
import itertools

**ZigZag Traverse**

In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix, up=0):
    out = []
    i, j = 0, 0

    while ((i+1) <= len(matrix)) and ((j+1) <= len(matrix[0])):
        out.append(matrix[i][j])
        if up==0:
            if ((j-1) < 0): i += 1; up = 1; continue
            elif ((i+1) == len(matrix)): j += 1; up = 1; continue
            if ((j-1) < 0) and ((i+1) == len(matrix)): j += 1; up = 1; continue
        else:
            if ((i-1) < 0): j += 1; up = 0; continue
            elif ((j+1) == len(matrix[0])): i += 1; up = 0; continue
            if ((i-1) < 0) and ((j+1) == len(matrix[0])): i += 1; up = 0; continue

        i += -1 if up else 1
        j += 1 if up else -1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[7 3 4 4 2 2 2 4 0]
 [0 8 3 6 4 9 4 3 4]
 [8 2 2 8 3 9 7 3 6]
 [7 9 9 0 3 5 4 3 2]] 
Output:
[7, 0, 3, 4, 8, 8, 7, 2, 3, 4, 2, 6, 2, 9, 9, 8, 4, 2, 2, 9, 3, 0, 3, 9, 4, 4, 0, 3, 7, 5, 4, 3, 4, 6, 3, 2]


In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix):
    out = []
    i, j = 0, 0
    rows = len(matrix)
    cols = len(matrix[0])
    up = 1

    while i < rows and j < cols:
        out.append(matrix[i][j])

        if up == 1:
            if j == 0 or i == rows - 1:
                up = 0
                if i == rows - 1:
                    j += 1
                else:
                    i += 1
            else:
                i += 1
                j -= 1
        else:
            if i == 0 or j == cols - 1:
                up = 1
                if j == cols - 1:
                    i += 1
                else:
                    j += 1
            else:
                i -= 1
                j += 1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[8 1]
 [1 1]
 [6 3]
 [5 7]
 [9 0]
 [8 0]
 [5 5]] 
Output:
[8, 1, 1, 1, 6, 5, 3, 7, 9, 8, 0, 0, 5, 5]


**Water Area**

In [ ]:
inList = np.random.randint(0, 30, size=180).tolist()

def trap(height):
    l = []
    m = max(height)
    for i in height:
        l.append([0]*(m-i) + [1]*i)
    l = np.array(l).T
    print(l)

    out = 0
    for i in l:
        for j in range(len(l[0])):
            if not i[j]==1:
                out += 1 if (1 in i[:j]) and (1 in i[j+1:]) else 0
    return out

def trap2(height):
    l = []
    r = []
    i, j, k = 0, height[0], height[-1]
    while i<len(height):
        j = j if height[i]<j else height[i]
        l.append(j)

        a = len(height)-i-1
        k = k if height[a]<k else height[a]
        r = [k]+r
        i+=1


    out = 0
    for i in range(len(height)):
        out += min(r[i], l[i]) - height[i]
    return out

print(f"{inList} \nOutput:\n{trap(inList)}")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[15, 10, 1, 26, 15, 20, 28, 1, 0, 13, 24, 10, 21, 16, 12, 4, 20, 9, 3, 18, 8, 8, 24, 15, 12, 18, 6, 20, 12, 26, 25, 11, 18, 10, 29, 18, 28, 17, 5, 20, 29, 16, 19, 27, 6, 19, 8, 29, 5, 11, 22, 24, 29, 9, 26, 20, 11, 21, 10, 10, 16, 17, 7, 6, 15, 8, 17, 3, 7, 24, 17, 4, 4, 26, 13, 3, 22, 29, 1, 6, 22, 25, 5, 12, 7, 18, 23, 12, 9, 19, 14, 12, 24, 17, 6, 23, 4, 4, 23, 24, 22, 8, 12, 23, 7, 1, 24, 25, 6, 9, 11, 25, 5, 17, 2, 25, 4, 5, 16, 22, 29, 8, 5, 6, 0, 6, 15, 28, 8, 18, 17, 6, 9, 1, 1, 0, 4, 15, 29, 20, 25, 29, 26, 3, 14, 20, 29, 29, 22, 1, 5, 18, 29, 27, 22, 22, 25, 4, 28, 14, 9, 10, 29, 24, 28, 21, 28, 28, 7, 18, 18, 28, 5, 19, 4, 9, 9, 22, 16, 22] 
Output:
2341


**Kth Largest Element**

In [ ]:
inList = np.random.randint(0, 30, size=15).tolist()

def kLargest(lis, k):
    out = 0
    l = [-i for i in lis]
    heapq.heapify(l)
    for i in range(k-1):
        heapq.heappop(l)
    return -heapq.heappop(l)

print(f"{inList} \nOutput:\n{kLargest(inList, 4)}")

[21, 27, 1, 18, 3, 6, 23, 15, 10, 19, 29, 19, 18, 7, 21] 
Output:
21


**Largest Rectangle Area**

In [ ]:
inList = np.random.randint(0, 30, size=15).tolist()

def largestArea(height):
        out = 0
        l = [0]*len(height)
        r = [0]*len(height)
        l[0] = -1
        r[-1] = len(height)

        for i in range(1, len(height)):
            p = i - 1

            while p >= 0 and height[p] >= height[i]:
                p = l[p]
            l[i] = p

        for i in range(len(height) - 2, -1, -1):
            p = i + 1

            while p < len(height) and height[p] >= height[i]:
                p = r[p]
            r[i] = p

        for i in range(len(height)):
            out = max(out, (r[i] - l[i] - 1)*height[i])
        return out

print(f"{inList} \nOutput:\n{largestArea(inList)}")

[16, 23, 16, 15, 15, 0, 18, 23, 3, 5, 6, 4, 19, 19, 5] 
Output:
75


**Last Digit of the Sum of Fibonacci Numbers**

In [ ]:
n = int(input())

def fib(n):
    a, b = 0, 1
    for i in range((n + 2) % 60):
        a, b = b, (a + b) % 10
    return 9 if a == 0 else a - 1

print(fib(n))

5


**Transpose Matrix**

In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10))).tolist()

head = lambda x : x[0]
tail = lambda x : x[1:]

def transposeMatrix(matrix):
    if not matrix or not matrix[0]:
        return []
    return [list(map(head, matrix))] + transposeMatrix(list(map(tail, matrix)))

print(f"{inMatrix} \nOutput:\n{transposeMatrix(inMatrix)}")

[[5, 4, 9, 9], [8, 3, 0, 9], [5, 3, 5, 6], [1, 7, 4, 5]] 
Output:
[[5, 8, 5, 1], [4, 3, 3, 7], [9, 0, 5, 4], [9, 9, 6, 5]]


**Merge Sorted Arrays**

In [ ]:
def mergeSortedArrays(arrays):
    return sorted(sum(arrays, []))

**First Non-Repeating Character**

In [ ]:
def firstNonRepeatingCharacter(string):
    s = {}
    for i in string:
        if i in s:
            s[i]+=1
        else:
            s[i]=1

    for i in range(len(string)):
        if s[string[i]]==1: return i
    return -1

**River Sizes**

In [ ]:
def helper(matrix, i, j):
    if i<0 or i>=len(matrix) or j<0 or j>=len(matrix[0]) or matrix[i][j]==0:
        return 0
    matrix[i][j]=0
    return helper(matrix, i+1, j)+helper(matrix, i-1, j)+helper(matrix, i, j+1)+helper(matrix, i, j-1)+1


def riverSizes(matrix):
    out = []
    for a in range(len(matrix)):
        for b in range(len(matrix[0])):
            if matrix[a][b] == 1:
                out.append(helper(matrix, a, b))
    return out

**Depth First Search**

In [ ]:
class Node:
    def __init__(self, name):
        self.children = []
        self.name = name

    def addChild(self, name):
        self.children.append(Node(name))
        return self

    def depthFirstSearch(self, array):
        if self.children==[]: return [self.name]
        return [self.name]+sum([i.depthFirstSearch(array) for i in self.children], [])

**Generate Document**

In [ ]:
from collections import Counter

def generateDocument(characters, document):
    s1 = Counter(characters)
    s2 = Counter(document)

    for i in s2.keys():
        if i not in s1 or s1[i] < s2[i]:
            return False
    return True

**Two Sum**

In [ ]:
def twoNumberSum(array, targetSum):
    out = []

    d = {}
    for i in array:
        if (targetSum-i) in d:
            out += [i, targetSum-i]
        else:
            d[i] = 0
    return out

**Ways to Traverse Graph**

In [ ]:
def numberOfWaysToTraverseGraph(width, height):
    if width<=1 and height<=1:
        return 1
    return (numberOfWaysToTraverseGraph(width-1, height) if width>1 else 0)+(numberOfWaysToTraverseGraph(width, height-1) if height>1 else 0)

**Heap Sort**

In [ ]:
import heapq
def heapSort(array):
    out = []
    heapq.heapify(array)
    for i in range(len(array)):
        out.append(heapq.heappop(array))
    return out

**Common Characters**

In [ ]:
def commonCharacters(strings):
    s = set(strings[0])
    for i in strings:
        s = s.intersection(set(i))
    return list(s)

**Group Anagrams**

In [ ]:
from collections import Counter

def groupAnagrams(words):
    s={}
    for i in words:
        if not s:
            s[i]=[Counter(i)]
            continue
        flag=0
        for j in s.keys():
            if Counter(i) == s[j][0]:
                s[j].append(i)
                flag=1
                break
        if not flag: s[i]=[Counter(i)]
    return [[i]+s[i][1:] for i in s.keys()]

**Sum of Linked Lists**

In [ ]:
class LinkedList:
    def __init__(self, value):
        self.value = value
        self.next = None


def sumOfLinkedLists(linkedListOne, linkedListTwo):
    tmp, tmp1=linkedListOne, linkedListTwo
    n = ["", ""]
    while tmp:
        n = [str(tmp.value)+n[0], n[1]]
        tmp = tmp.next
    while tmp1:
        n = [n[0], str(tmp1.value)+n[1]]
        tmp1 = tmp1.next

    n = str(sum(list(map(int, n))))[::-1]
    head = LinkedList(int(n[0]))
    tmp, tmp1 = head, None
    i=1
    while i<len(n):
        tmp1 = LinkedList(int(n[i]))
        tmp.next = tmp1
        tmp = tmp1
        i+=1
    return head

**Majority Element**

In [ ]:
from collections import Counter
def majorityElement(array):
    return max(array,key=array.count)

**Permutations**

In [ ]:
def getPermutations(array):
    if len(array)==1: return [array]
    out = []
    for i in range(len(array)):
        out += list(map(lambda x:[array[i]]+x, getPermutations(array[:i]+array[i+1:])))
    return out
print(getPermutations(list(range(7))))

[[0, 1, 2, 3, 4, 5, 6], [0, 1, 2, 3, 4, 6, 5], [0, 1, 2, 3, 5, 4, 6], [0, 1, 2, 3, 5, 6, 4], [0, 1, 2, 3, 6, 4, 5], [0, 1, 2, 3, 6, 5, 4], [0, 1, 2, 4, 3, 5, 6], [0, 1, 2, 4, 3, 6, 5], [0, 1, 2, 4, 5, 3, 6], [0, 1, 2, 4, 5, 6, 3], [0, 1, 2, 4, 6, 3, 5], [0, 1, 2, 4, 6, 5, 3], [0, 1, 2, 5, 3, 4, 6], [0, 1, 2, 5, 3, 6, 4], [0, 1, 2, 5, 4, 3, 6], [0, 1, 2, 5, 4, 6, 3], [0, 1, 2, 5, 6, 3, 4], [0, 1, 2, 5, 6, 4, 3], [0, 1, 2, 6, 3, 4, 5], [0, 1, 2, 6, 3, 5, 4], [0, 1, 2, 6, 4, 3, 5], [0, 1, 2, 6, 4, 5, 3], [0, 1, 2, 6, 5, 3, 4], [0, 1, 2, 6, 5, 4, 3], [0, 1, 3, 2, 4, 5, 6], [0, 1, 3, 2, 4, 6, 5], [0, 1, 3, 2, 5, 4, 6], [0, 1, 3, 2, 5, 6, 4], [0, 1, 3, 2, 6, 4, 5], [0, 1, 3, 2, 6, 5, 4], [0, 1, 3, 4, 2, 5, 6], [0, 1, 3, 4, 2, 6, 5], [0, 1, 3, 4, 5, 2, 6], [0, 1, 3, 4, 5, 6, 2], [0, 1, 3, 4, 6, 2, 5], [0, 1, 3, 4, 6, 5, 2], [0, 1, 3, 5, 2, 4, 6], [0, 1, 3, 5, 2, 6, 4], [0, 1, 3, 5, 4, 2, 6], [0, 1, 3, 5, 4, 6, 2], [0, 1, 3, 5, 6, 2, 4], [0, 1, 3, 5, 6, 4, 2], [0, 1, 3, 6, 2, 4, 5], [0, 1, 3, 

In [ ]:
print(timeit.timeit("[i for i in itertools.permutations(list(range(3)))]"))
print(timeit.timeit("""
def getPermutations(array):
    if len(array) <= 1: return [array] if len(array)==1 else []
    return [p[:i] + [array[0]] + p[i:] for p in getPermutations(array[1:]) for i in range(len(p) + 1)]
getPermutations(list(range(3)))"""))

1.1911552750000283
5.480886018999968


**Node Depth Sum**

In [ ]:
def nodeDepths(root, depth=0):
    if not root: return 0
    return depth+nodeDepths(root.left, depth+1)+nodeDepths(root.right, depth+1)

**Min Characters**

In [ ]:
def minimumCharactersForWords(words):
    s = {}
    for i in words:
        for j in i:
            if j in s:
                s[j][0] += 1
            else:
                s[j] = [1, 0]
        s = {i:[0, s[i][0 if s[i][0] > s[i][1] else 1]] for i in s}
    return sum([[i]*s[i][1] for i in s], [])

**Branch Sum**

In [ ]:
def branchSums(root):
    if not root: return []
    branches = branchSums(root.left)+branchSums(root.right)
    return [root.value+i for i in branches] if branches else [root.value]

**Symetrical Tree**

In [ ]:
def helper(left, right):
    if left and right and left.value==right.value:
        return helper(left.left, right.right) and helper(left.right, right.left)
    return left==right

def symmetricalTree(root):
    return helper(root.left, root.right)

**Longest Palindrome**

In [ ]:
def longestPalindromicSubstring(string):
    if len(string)<=1: return string
    out = ""
    for i in range(len(string)):
        for j in range(i, len(string)+1):
            sub = string[i:j]
            if len(sub)>len(out) and (sub==sub[::-1]):
                out = sub
    return out

**Longest Peak**

In [ ]:
def longestPeak(array):
    if array==[]: return 0
    p = []
    out = []
    for i in range(0, len(array)-2):
        if array[i]<array[i+1]>array[i+2]:
            p.append([i+1, 1])
            continue
        if array[i]>array[i+1]<array[i+2]:
            p.append([i+1, 0])
            continue
        if array[i]==array[i+1] or array[i+1]==array[i+2]:
            p.append([i+1, 0])
            continue

    i=0
    while i<len(p):
        if p[i][1]==1:
            l, h = 0 if i<1 else p[i-1][0], (len(array)-1) if i>=(len(p)-1) else p[i+1][0]
            out.append(abs(h-l)+1)
        i+=1
    return max(out, default=0)

**Tournament Winner**

In [ ]:
def tournamentWinner(competitions, results):
    d = {}
    for (winner, loser), result in zip(competitions, results):
        d[winner if result else loser] = d.get(winner if result else loser, 0) + 3
    return max(d, key=d.get)

**Colliding Asteroids**

In [ ]:
def collidingAsteroids(asteroids):
    stack = []

    for asteroid in asteroids:
        while stack and asteroid < 0 < stack[-1]:
            if abs(asteroid) > stack[-1]:
                stack.pop()
                continue
            elif abs(asteroid) == stack[-1]:
                stack.pop()
            break
        else:
            stack.append(asteroid)
    return stack

**Knapsack Problem**

In [ ]:
def knapsackProblem(items, capacity):
    n = len(items)
    dp = [[0] * (capacity + 1) for _ in range(n + 1)]

    for i in range(1, n + 1):
        value, weight = items[i - 1]
        for w in range(capacity + 1):
            if weight > w:
                dp[i][w] = dp[i - 1][w]
            else:
                dp[i][w] = max(dp[i - 1][w], dp[i - 1][w - weight] + value)

    # Backtrack to find the selected items
    selected_items = []
    i, w = n, capacity
    while i > 0 and w > 0:
        if dp[i][w] != dp[i - 1][w]:
            selected_items.append(i - 1)
            w -= items[i - 1][1]
        i -= 1

    selected_items.reverse()
    return [dp[n][capacity], selected_items]

**Topological Sort**

In [ ]:

def topologicalSort(jobs, deps):
    adj = {i:[] for i in jobs}
    for i in deps:
        adj[i[0]].append(i[1])
    nodes = [i for i in jobs if not any(j[1]==i for j in deps)]
    visited = set()
    out = []
    def dfs(node, stack=[]):
        if node in stack:
            return False
        if node in visited:
            return True

        visited.add(node)
        stack.append(node)

        for i in adj[node]:
            if not dfs(i, stack):
                return False

        stack.pop()
        out.append(node)
        return True

    valid = False
    while nodes:
        n = nodes.pop(0)
        if n in visited:
            continue
        valid = dfs(n)
    return out[::-1] if valid else []

**Quickselect**

In [ ]:
import heapq
def quickselect(array, k):
    heapq.heapify(array)

    for i in range(k-1):
        heapq.heappop(array)
    return heapq.heappop(array)

**Two Colorable**

In [ ]:
def twoColorable(edges):
    if len(edges) <= 1:
        return False

    c0, c1 = set([0]), set()
    s = [[0, 0]]
    while s:
        node = s.pop(0)
        if node[1] == 1:
            if any(neigh in c1 for neigh in edges[node[0]]):
                return False
            s += [[i, 0] for i in edges[node[0]] if i not in c0]
            c0.update(edges[node[0]])
        else:
            if any(neigh in c0 for neigh in edges[node[0]]):
                return False
            s += [[i, 1] for i in edges[node[0]] if i not in c1]
            c1.update(edges[node[0]])
    return True

**Max Submatrix Sum**

In [ ]:
import math
matrixSum = lambda m: sum(sum(i) for i in m)
def maximumSumSubmatrix(matrix, size):
    m=-math.inf
    for i in range(len(matrix)-size+1):
        for j in range(len(matrix[0])-size+1):
            subMatrix=[a[j:j+size] for a in matrix[i:i+size]]
            m=max(m, matrixSum(subMatrix))
    return m

def maximumSumSubmatrix(matrix, size):
    def matrixSum(matrix):
        return sum(sum(row) for row in matrix)

    m = float('-inf')
    for i in range(len(matrix) - size + 1):
        for j in range(len(matrix[0]) - size + 1):
            subMatrix = [row[j:j+size] for row in matrix[i:i+size]]
            subMatrixSum = matrixSum(subMatrix)
            m = max(m, subMatrixSum)
    return m

**Flatten Binary Tree**

In [ ]:
class BinaryTree:
    def __init__(self, value, left=None, right=None):
        self.value = value
        self.left = left
        self.right = right

def inorder(root):
    if not root: return []
    return inorder(root.left)+[root.value]+inorder(root.right)

def flattenBinaryTree(root):
    out = inorder(root)
    tmp=None
    head=None
    for i in out:
        node = BinaryTree(i, tmp, None)
        if tmp:
            tmp.right = node
        else:
            head=node
        tmp = node
    return head

**Find Loop**

In [ ]:
def findLoop(head):
    visited = set()
    tmp=head
    while tmp:
        if tmp in visited:
            return tmp
        visited.add(tmp)
        tmp=tmp.next
    return None

**Iterative Inorder**

In [ ]:
def iterativeInOrderTraversal(tree, callback):
    visited = []
    tmp = tree
    while tmp:
        if tmp.left!=None and tmp.left not in visited:
            tmp = tmp.left
            continue
        if tmp not in visited:
            callback(tmp)
            visited.append(tmp)
            continue
        if tmp.right!=None and tmp.right not in visited:
            tmp = tmp.right
            continue
        tmp = tmp.parent

**Merge Sort**

In [ ]:
def merge(arr1, arr2):
    out = []
    while (0<len(arr1)) and (0<len(arr2)):
        a, b = arr1[0], arr2[0]
        if a<b:
            out.append(a)
            arr1.pop(0)
        else:
            out.append(b)
            arr2.pop(0)
    return out+arr1+arr2

def mergeSort(array):
    if len(array)<=1: return array
    return merge(mergeSort(array[:len(array)//2]), mergeSort(array[len(array)//2:]))

**Index Equals Value**

In [ ]:
def indexEqualsValue(array):
    for i in range(len(array)):
        if i==array[i]:
            return i
    return -1