<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random
import numpy as np
import heapq

**ZigZag Traverse**

In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix, up=0):
    out = []
    i, j = 0, 0

    while ((i+1) <= len(matrix)) and ((j+1) <= len(matrix[0])):
        out.append(matrix[i][j])
        if up==0:
            if ((j-1) < 0): i += 1; up = 1; continue
            elif ((i+1) == len(matrix)): j += 1; up = 1; continue
            if ((j-1) < 0) and ((i+1) == len(matrix)): j += 1; up = 1; continue
        else:
            if ((i-1) < 0): j += 1; up = 0; continue
            elif ((j+1) == len(matrix[0])): i += 1; up = 0; continue
            if ((i-1) < 0) and ((j+1) == len(matrix[0])): i += 1; up = 0; continue

        i += -1 if up else 1
        j += 1 if up else -1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[7 3 4 4 2 2 2 4 0]
 [0 8 3 6 4 9 4 3 4]
 [8 2 2 8 3 9 7 3 6]
 [7 9 9 0 3 5 4 3 2]] 
Output:
[7, 0, 3, 4, 8, 8, 7, 2, 3, 4, 2, 6, 2, 9, 9, 8, 4, 2, 2, 9, 3, 0, 3, 9, 4, 4, 0, 3, 7, 5, 4, 3, 4, 6, 3, 2]


In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix):
    out = []
    i, j = 0, 0
    rows = len(matrix)
    cols = len(matrix[0])
    up = 1

    while i < rows and j < cols:
        out.append(matrix[i][j])

        if up == 1:
            if j == 0 or i == rows - 1:
                up = 0
                if i == rows - 1:
                    j += 1
                else:
                    i += 1
            else:
                i += 1
                j -= 1
        else:
            if i == 0 or j == cols - 1:
                up = 1
                if j == cols - 1:
                    i += 1
                else:
                    j += 1
            else:
                i -= 1
                j += 1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[8 1]
 [1 1]
 [6 3]
 [5 7]
 [9 0]
 [8 0]
 [5 5]] 
Output:
[8, 1, 1, 1, 6, 5, 3, 7, 9, 8, 0, 0, 5, 5]


**Water Area**

In [ ]:
inList = np.random.randint(0, 30, size=180).tolist()

def trap(height):
    l = []
    m = max(height)
    for i in height:
        l.append([0]*(m-i) + [1]*i)
    l = np.array(l).T
    print(l)

    out = 0
    for i in l:
        for j in range(len(l[0])):
            if not i[j]==1:
                out += 1 if (1 in i[:j]) and (1 in i[j+1:]) else 0
    return out

print(f"{inList} \nOutput:\n{trap(inList)}")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[15, 10, 1, 26, 15, 20, 28, 1, 0, 13, 24, 10, 21, 16, 12, 4, 20, 9, 3, 18, 8, 8, 24, 15, 12, 18, 6, 20, 12, 26, 25, 11, 18, 10, 29, 18, 28, 17, 5, 20, 29, 16, 19, 27, 6, 19, 8, 29, 5, 11, 22, 24, 29, 9, 26, 20, 11, 21, 10, 10, 16, 17, 7, 6, 15, 8, 17, 3, 7, 24, 17, 4, 4, 26, 13, 3, 22, 29, 1, 6, 22, 25, 5, 12, 7, 18, 23, 12, 9, 19, 14, 12, 24, 17, 6, 23, 4, 4, 23, 24, 22, 8, 12, 23, 7, 1, 24, 25, 6, 9, 11, 25, 5, 17, 2, 25, 4, 5, 16, 22, 29, 8, 5, 6, 0, 6, 15, 28, 8, 18, 17, 6, 9, 1, 1, 0, 4, 15, 29, 20, 25, 29, 26, 3, 14, 20, 29, 29, 22, 1, 5, 18, 29, 27, 22, 22, 25, 4, 28, 14, 9, 10, 29, 24, 28, 21, 28, 28, 7, 18, 18, 28, 5, 19, 4, 9, 9, 22, 16, 22] 
Output:
2341


**Kth Largest Element**

In [6]:
inList = np.random.randint(0, 30, size=15).tolist()

def kLargest(lis, k):
    out = 0
    heapq.heapify([-i for i in lis])
    for i in range(k-1):
        heapq.heappop([-i for i in lis])
    return -heapq.heappop([-i for i in lis])

print(f"{inList} \nOutput:\n{kLargest(inList, 4)}")

[11, 22, 17, 24, 7, 13, 21, 4, 23, 26, 18, 0, 6, 6, 7] 
Output:
11
