<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import random
import numpy as np

**ZigZag Traverse**

In [ ]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix, up=0):
    out = []
    i, j = 0, 0

    while ((i+1) <= len(matrix)) and ((j+1) <= len(matrix[0])):
        out.append(matrix[i][j])
        if up==0:
            if ((j-1) < 0): i += 1; up = 1; continue
            elif ((i+1) == len(matrix)): j += 1; up = 1; continue
            if ((j-1) < 0) and ((i+1) == len(matrix)): j += 1; up = 1; continue
        else:
            if ((i-1) < 0): j += 1; up = 0; continue
            elif ((j+1) == len(matrix[0])): i += 1; up = 0; continue
            if ((i-1) < 0) and ((j+1) == len(matrix[0])): i += 1; up = 0; continue

        i += -1 if up else 1
        j += 1 if up else -1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[7 3 4 4 2 2 2 4 0]
 [0 8 3 6 4 9 4 3 4]
 [8 2 2 8 3 9 7 3 6]
 [7 9 9 0 3 5 4 3 2]] 
Output:
[7, 0, 3, 4, 8, 8, 7, 2, 3, 4, 2, 6, 2, 9, 9, 8, 4, 2, 2, 9, 3, 0, 3, 9, 4, 4, 0, 3, 7, 5, 4, 3, 4, 6, 3, 2]


In [3]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix):
    out = []
    i, j = 0, 0
    rows = len(matrix)
    cols = len(matrix[0])
    up = 1

    while i < rows and j < cols:
        out.append(matrix[i][j])

        if up == 1:
            if j == 0 or i == rows - 1:
                up = 0
                if i == rows - 1:
                    j += 1
                else:
                    i += 1
            else:
                i += 1
                j -= 1
        else:
            if i == 0 or j == cols - 1:
                up = 1
                if j == cols - 1:
                    i += 1
                else:
                    j += 1
            else:
                i -= 1
                j += 1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[8 1]
 [1 1]
 [6 3]
 [5 7]
 [9 0]
 [8 0]
 [5 5]] 
Output:
[8, 1, 1, 1, 6, 5, 3, 7, 9, 8, 0, 0, 5, 5]
