<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import random
import numpy as np

**ZigZag Traverse**

In [24]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix, up=0):
    out = []
    i, j = 0, 0

    while ((i+1) <= len(matrix)) and ((j+1) <= len(matrix[0])):
        out.append(matrix[i][j])
        if up==0:
            if ((j-1) < 0): i += 1; up = 1; continue
            elif ((i+1) == len(matrix)): j += 1; up = 1; continue
            if ((j-1) < 0) and ((i+1) == len(matrix)): j += 1; up = 1; continue
        else:
            if ((i-1) < 0): j += 1; up = 0; continue
            elif ((j+1) == len(matrix[0])): i += 1; up = 0; continue
            if ((i-1) < 0) and ((j+1) == len(matrix[0])): i += 1; up = 0; continue

        i += -1 if up else 1
        j += 1 if up else -1
    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[5 1 0 3 4 3 2 1 9]
 [4 3 0 4 1 0 0 6 2]
 [2 9 2 7 2 5 7 2 1]
 [3 4 2 0 4 1 0 0 8]
 [5 5 4 7 7 6 9 4 8]
 [0 1 2 3 1 9 9 1 0]
 [3 0 9 9 6 3 8 8 3]
 [8 7 0 8 6 5 8 2 5]] 
Output:
[5, 4, 1, 0, 3, 2, 3, 9, 0, 3, 4, 4, 2, 4, 5, 0, 5, 2, 7, 1, 3, 2, 0, 2, 0, 4, 1, 3, 8, 0, 2, 7, 4, 5, 0, 1, 9, 6, 7, 1, 7, 3, 9, 7, 0, 9, 1, 6, 0, 2, 2, 1, 0, 9, 9, 6, 8, 6, 3, 9, 4, 8, 8, 1, 8, 5, 8, 8, 0, 3, 2, 5]
