<a href="https://colab.research.google.com/github/cardstdani/algorithms/blob/main/AlgorithmList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import random
import numpy as np

**ZigZag Traverse**

In [18]:
inMatrix  = np.random.randint(0,10,(random.randint(1, 10),random.randint(1, 10)))

def zigZag(matrix, up=0):
    out = []
    i, j = 0, 0

    while ((i+1) < len(matrix)) and ((j+1) < len(matrix[0])):
        out.append(matrix[i][j])
        if not up:
            if ((j-1) < 0): i += 1; up = 1; continue
            elif ((i+1) == len(matrix)): j += 1; up = 1; continue
        else:
            if ((i-1) < 0): j += 1; up = 0; continue
            elif ((j+1) == len(matrix[0])): i += 1; up = 0; continue

        i += 1 if up else -1
        j += 1 if up else -1

    return out

print(f"{inMatrix} \nOutput:\n{zigZag(inMatrix)}")

[[1 0 1 6 8 9 3 9]
 [5 9 5 2 0 9 3 8]
 [0 8 4 1 8 9 5 5]] 
Output:
[1, 5]
